export default {
    f1:{
        flex:1,
    },
    f2:{
        flex:2,
    },
    f3:{
        flex:3,
    },
    f4:{
        flex:4,
    },
    f5:{
        flex:5,
    },
    f6:{
        flex:6,
    },
    f7:{
        flex:7,
    },
    f8:{
        flex:8,
    },
    csmall:{
        fontSize:14
    },
    csmid:{
        fontSize:16  
    },
    cmid:{
        fontSize:18
    },
    cbmid:{
        fontSize:20
    },
    clmid:{
        fontSize:22
    },
    cbig:{
        fontSize:24
    },
    cw:{
        color:'#fff'
    },
    mt10:{
        marginTop:10
    },
    mt20:{
        marginTop:20
    },
    mt30:{
        marginTop:30
    },
    ml10:{
        marginLeft:10
    },
    ml20:{
        marginLeft:20
    },
    ml30:{
        marginLeft:30
    },
    mr10:{
        marginRight:10
    },
    mr20:{
        marginRight:20
    },
    mr30:{
        marginRight:30
    },
    mb10:{
        marginBottom:10
    },
    mb20:{
        marginBottom:20
    },
    mb30:{
        marginBottom:30
    },
    pb10:{
        paddingBottom:10
    },
    pb20:{
        paddingBottom:20
    },
    pb30:{
        paddingBottom:30
    },
    pt10:{
        paddingTop:10
    },
    pt20:{
        paddingTop:20
    },
    pt30:{
        paddingTop:30
    },
    flexCenter:{
        alignItems:'center',justifyContent:'center'
    },
    flexRow:{
        flexDirection: 'row'
    },
    cpink:{color:'#d2004f'},
    ccyan:{color:'#1abc9c'},//青色
    cgreen:{color:'#2ecc71'},//绿色
    cblue:{color:'#3498db'},//蓝色
    cpurple:{color:'#1abc9c'},//紫色
    cdblue:{color:'#34495e'},//深蓝
    cyellow:{color:'#34495e'},//黄色
    corange:{color:'#e67e22'},//橙色
    cred:{color:'#e74c3c'},//红色
    cwhite:{color:'#ecf0f1'},//白色
    cgray:{color:'#95a5a6'},//灰色
    czhi:{color:'rgb(43,123,225)'},//知乎蓝
    //
    
    ccyanH:{color:'#16a085'},
    cgreenH:{color:'#27ae60'},
    cblueH:{color:'#2980b9'},
    cpurpleH:{color:'#8e44ad'},
    cdblueH:{color:'#2c3e50'},
    cyellowH:{color:'#f39c12'},//黄色
    corangeH:{color:'#d35400'},//橙色
    credH:{color:'#c0392b'},//红色
    cwhiteH:{color:'#bdc3c7'},//白色
    cgrayH:{color:'#7f8c8d'},//灰色

    bpink:{backgroundColor:'#d2004f'},
    bpwhite:{backgroundColor:'#ffffff'},
    bcyan:{backgroundColor:'#1abc9c'},//青色
    bgreen:{backgroundColor:'#2ecc71'},//绿色
    bblue:{backgroundColor:'#3498db'},//蓝色
    bpurple:{backgroundColor:'#1abc9c'},//紫色
    bdblue:{backgroundColor:'#34495e'},//深蓝
    byellow:{backgroundColor:'#34495e'},//黄色
    borange:{backgroundColor:'#e67e22'},//橙色
    bred:{backgroundColor:'#e74c3c'},//红色
    bwhite:{backgroundColor:'#ecf0f1'},//白色
    bgray:{backgroundColor:'#95a5a6'},//灰色
    btrans:{backgroundColor:'transparent'},//透明
    //
    bcyanH:{backgroundColor:'#16a085'},
    bgreenH:{backgroundColor:'#27ae60'},
    bblueH:{backgroundColor:'#2980b9'},
    bpurpleH:{backgroundColor:'#8e44ad'},
    bdblueH:{backgroundColor:'#2c3e50'},
    byellowH:{backgroundColor:'#f39c12'},//黄色
    borangeH:{backgroundColor:'#d35400'},//橙色
    bredH:{backgroundColor:'#c0392b'},//红色
    bwhiteH:{backgroundColor:'#bdc3c7'},//白色
    bgrayH:{backgroundColor:'#7f8c8d'},//灰色
}